- name: Render daemon.json
  become: true
  template:
    src: ./daemon.json.j2
    dest: /etc/docker/daemon.json
    group: root
    owner: root
    mode: 0444
  notify:
    - Restart containers infra
