- name: Ensure portainer's directory
  become: true
  ansible.builtin.file:
    path: "{{ docker.portainer.install_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0555"

- name: Render portainer's compose
  become: true
  ansible.builtin.template:
    src: ./portainer/docker-compose.yaml.j2
    dest: "{{ '/'.join((docker.portainer.install_dir, 'docker-compose.yaml')) }}"
    group: root
    owner: root
    mode: 0444
  notify: Restart portainer

- name: Render portainer's unit file
  become: true
  ansible.builtin.template:
    src: ./portainer/service.j2
    dest: /etc/systemd/system/portainer.service
    owner: root
    group: root
    mode: "0444"
  notify: Restart portainer
  register: render_portainer_unit

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: render_portainer_unit.changed

- name: Enable portainer
  become: true
  ansible.builtin.service:
    name: portainer.service
    enabled: true
    state: started
