- name: Render daemon.json
  become: true
  template:
    src: ./daemon.json.j2
    dest: /etc/docker/daemon.json
    group: root
    owner: root
    mode: 0444
  notify:
    - Restart containers infra

- name: Disable IPv6 system-wide
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    state: present
    value: "1"
    sysctl_file: /etc/sysctl.d/20-disable-ipv6.conf
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
