- name: Enable docker and container.d
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - docker.service
    - containerd.service
