- name: Setup docker's apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: '{{ ansible_facts.distribution_release }}'
    components: stable
    architectures: '{{ deb_architecture[ansible_facts.architecture] }}'
    signed_by: https://download.docker.com/linux/ubuntu/gpg
  register: apt_repo

- name: Update apt's cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: apt_repo.changed

  # Need this for CIFS-volumes to work properly with UTF-8
- name: Setup extra kernel stuff (install)
  become: true
  ansible.builtin.apt:
    name: linux-image-extra-virtual
    state: present

- name: Setup docker's package (install)
  become: true
  ansible.builtin.apt:
    name: "docker-ce={{ docker.version }}"
    state: present
  notify:
    - Restart containers infra

- name: Hold docker's packages
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - docker-ce
    - docker-ce-rootless-extras
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
