- name: Setup docker's apt key
  become: true
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Setup docker's apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  register: apt_repo

- name: Update apt's cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: apt_repo.changed

- name: Setup docker's package (install)
  become: true
  ansible.builtin.apt:
    name: "docker-ce={{ docker.version }}"
    state: present
  notify:
    - Restart containers infra

- name: Hold docker's packages
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
