- name: Prepare facts
  ansible.builtin.import_tasks: prepare_facts.yaml
  tags: [ portainer ]

- name: Setup/install docker
  ansible.builtin.import_tasks: install_docker.yaml

- name: Configure docker
  ansible.builtin.import_tasks: configure_docker.yaml

- name: Enable and start docker
  ansible.builtin.import_tasks: enable_start_docker.yaml

- name: Add provision fact
  ansible.builtin.import_tasks: mark_host_as_docker_provisioned.yaml

- name: Configure portainer
  ansible.builtin.import_tasks: configure_portainer.yaml
  tags: [ portainer ]

- name: Allow 'me' to use docker
  become: true
  ansible.builtin.user:
    name: "{{ me }}"
    append: true
    groups:
      - docker
  when: me is defined
