- name: Prepare facts
  include: prepare_facts.yaml

- name: Setup/install docker
  become: true
  include: install_docker.yaml

- name: Configure docker
  become: true
  include: configure_docker.yaml

- name: Enable and start docker
  become: true
  include: enable_start_docker.yaml

- name: Configure portainer
  become: true
  include: configure_portainer.yaml

- name: Allow 'me' to use docker
  become: true
  ansible.builtin.user:
    name: "{{ me }}"
    append: true
    groups:
      - docker
  when: me is defined
