- name: Put local facts directory
  become: true
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode:  "0755"

- name: Put local fact for provisioned docker
  become: true
  ansible.builtin.template:
    src: ./docker.fact.j2
    dest: /etc/ansible/facts.d/docker.fact
    group: root
    owner: root
    mode: 0444
